## 数据源配置
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456
      #初始化连接数量，最大最小连接数
      initial-size: 5
      max-active: 10
      min-idle: 3
      #获取连接等待超时的时间
      max-wait: 600000

      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 600000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 1000000 #300000
      #用来检测连接是否有效的sql，要求是一个查询语句
      validation-query: SELECT 1
      #申请连接的时候检测
      test-while-idle: true
      #申请连接时执行validationQuery检测连接是否有效，配置为true会降低性能
      test-on-borrow: false
      #归还连接时执行validationQuery检测连接是否有效，配置为true会降低性能
      test-on-return: false
      #打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 50
      #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：
      #监控统计用的filter:stat 日志用的filter:log4j 防御SQL注入的filter:wall
      filters: stat

      stat-view-servlet:
        #allow: '*'
        #deny: 172.16.0.117
        login-username: druid
        login-password: druidzzlc123
        reset-enable: false
        url-pattern: '/druid/*'

      web-stat-filter:
        url-pattern: '/*'
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'



  mvc:
    static-path-pattern: /**

  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 1024
      max-request-size: 1024

#端口
server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8

mybatis:
  type-aliases-package: com.example.transactiondemo.domain
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: com.example.transactiondemo.dao
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 1000 #30
    call-setters-on-nulls: true
